### PR TITLE
remove sle2docker recommendation. fixes bsc#1032663

### PR DESCRIPTION
**Pull request by jordimassaguerpla**

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
This is correct, as sle2docker is no longer compatible with native images builds 👍

**Comment by davidcassany** [comment]
@jordimassaguerpla not sure if it would make any sense to include a recommendation to container-feeder? I woudn't do that, but if fact it is likely to be the successor of sle2docker.

**Comment by jordimassaguerpla** [comment]
@davidcassany : Maybe later because this containment-rpm-docker is being used also for other docker images which are not being used in the kubik project and that change would break it, unless we made container-feeder available to them as well.

**Comment by davidcassany** [comment]
makes sense 👍

**Pull request merged**
