### PR TITLE
Make changelog-generator optional for openSUSE

### LINKED ISSUE #31: Make changelog-generator optional
The .changes files aren't needed in openSUSE, so we don't need to have rubygem(changelog-generator) and changelog-generator-data in the distribution just to wrap the images in RPM packages.

### PR DESCRIPTION
**Pull request by Vogtinator**
Fixes #31

### CODE REVIEW

**Review by davidcassany — CHANGES_REQUESTED** [review]
With this change the kiwi_post_run could fail under some circumstances. I would also update kiwi_post_run script to only run changelog generator if the tool is present.

Probably something like:

```bash
if type changelog-generator &> /dev/null; then
   <call changelog and whatever is need>
fi

**Comment by Vogtinator** [comment]
> With this change the kiwi_post_run could fail under some circumstances.

Yes, if changelog data is installed.

What about printing an error message and doing `exit 1` if a changelog was found but no changelog-generator is installed?

**Comment by davidcassany** [comment]
@Vogtinator This sounds good, as if the changelog is there I guess you want to make use of it. Even I am not sure this is a possible scenario given the requirements of the packages, better to stay on the safe side and consider it.

**Review by jordimassaguerpla — DISMISSED** [review]
What about, instead of removing the requirements for openSUSE, replacing the Requires by Recommends.

This way, if the packages are not there, they won't be used.

My concern is that your change is breaking backward compatibility. A user which we don't know may be using containment-rpm-docker with openSUSE ... I am not aware of the case and I think is very unlikely, but still I think is a good practice.

**Comment by Vogtinator** [comment]
> What about, instead of removing the requirements for openSUSE, replacing the Requires by Recommends.
> 
> This way, if the packages are not there, they won't be used.

No, they'll never be used. OBS ignores recommends during dependency resolution so you would need to add them to the prjconf manually.

> My concern is that your change is breaking backward compatibility. A user which we don't know may be using containment-rpm-docker with openSUSE ... I am not aware of the case and I think is very unlikely, but still I think is a good practice.

There's no way to fix that though.

**Comment by Vogtinator** [comment]
kiwi_post_run now checks for `changelog-generator`.

**Comment by Vogtinator** [comment]
I pushed to the wrong branch, change is now part of this PR as well...

**Review by davidcassany — APPROVED** [review]
Looks good to me

**Pull request merged**
