### PR TITLE
packaging: make branch configurable

### PR DESCRIPTION
**Pull request by MaximilianMeister**
Signed-off-by: Maximilian Meister <mmeister@suse.de>

### NOTE

This is related to our packaging automation to support stable branch packaging

### DEPENDS ON

https://gitlab.suse.de/MaximilianMeister/automation/commit/6b686a21797515813963a397927e3811ef7f386b within https://gitlab.suse.de/docker/automation/merge_requests/148

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
[EPIC: Migrate infrastructure to stable release projects](https://trello.com/c/LFrQYvHY/283-epic-migrate-infrastructure-to-stable-release-projects)

**Comment by davidcassany** [comment]
@MaximilianMeister looks fine to me, I managed to build our sles12 images using a container-rpm-docker that makes use of that patch and everything went fine. Before setting the PR as approved I'd like share just a couple of comments I noticed trying to rebuild the package with the present patch:

- I noticed that looks like concourse is not making use of the OBS _service file to update the package. Is that correct? if so, I'd suggest to completely remove the _service file, even it is in disabled mode, as it is confusing, I would expect that enabling the service would correctly updated the package, but looks like this is not the case. Maybe I miss something, I am not completely aware about how concourse submits changes to the OBS.

- I could not figure out how the concourse makes the source tarball and if the change [here](https://gitlab.suse.de/MaximilianMeister/automation/commit/6b686a21797515813963a397927e3811ef7f386b) is in line with this PR. Anyway it looks odd to me to include a source tarball having the root folder called `container-rpm-docker-<branch>` why do we have to include the branch here?

**Comment by MaximilianMeister** [comment]
> I noticed that looks like concourse is not making use of the OBS _service file to update the package. Is that correct? if so, I'd suggest to completely remove the _service file, even it is in disabled mode, as it is confusing, I would expect that enabling the service would correctly updated the package, but looks like this is not the case.

the issue with this is that we do a copypac from obs to ibs once we have a green build in obs, and the copypac would also copy the _service file to ibs. then after a green build in ibs we are submitting the very same package to the product in the end, and there we can't have an activated _service file.
I am not really sure why we still have it, maybe @jordimassaguerpla knows more details there?

> Anyway it looks odd to me to include a source tarball having the root folder called container-rpm-docker-<branch> why do we have to include the branch here?

that's a given automatism from github, if you use their tarball download endpoint, they will give you a tarball with this `$reponame-$branch` inside.

**Comment by davidcassany** [comment]
Oh, thanks @MaximilianMeister, I haven't used the tarball download in github for a while, I did not realize that the source tarball name was created by github itself. 

Then I insist on cleaning the containment-rpm-docker pacakge in obs, because there is still the old source tarball there, which is not used in spec. After merging this I would just delete `_service` file and any other unused file. @jordimassaguerpla, do you have anything against removing the `_service` file from Virtualization:containers:images/containment-rpm-docker?

**Review by davidcassany — APPROVED** [review]
Looks good to me 👍

**Comment by jordimassaguerpla** [comment]
This request LGTM, but I am not sure about the whole idea.

This idea of packaging branches is for packages under devel:CaaSP project in obs, which are specific for SUSE CaaSP.

However, containment-rpm-docker is a bit more generic and so it belongs to the Virtualization:containers:images repo and thus others may be using it. So I would rather prefer to use the "classic" approach of versioning and using a disabled _service file in obs, as we do for other packages under Virtualization:containers, like kubernetes, etcd, docker, etc..

Then, I would link that package to devel:CaaSP and use our CI (concourse) to copy that package to our test/release repos.

**Comment by MaximilianMeister** [comment]
@jordimassaguerpla makes sense. anyways this change will not change the workflow, as we're always falling back to master. so this would be ok to merge in any case

**Review by jordimassaguerpla — APPROVED** [review]

**Pull request merged**
